In [47]:
import numpy as np
from sklearn import preprocessing, svm, model_selection, neighbors, svm
from sklearn.model_selection import train_test_split
import pandas as pd

In [49]:
df = pd.read_csv('breast-cancer-wisconsin.data')
df.replace('?', -99999, inplace = True)
#id has no implication to the algorithm, its an outlier
df.drop('id', axis=1, inplace = True)
df

,clump_thickness,unif_cell_size,unif_cell_shape,marg_adhesion,single_epith_cell_size,bare_nuclei,cland_chrom,norm_nucleoli,mitoses,class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...
694,3,1,1,1,3,2,1,1,1,2
695,2,1,1,1,2,1,1,1,1,2
696,5,10,10,3,7,3,8,10,2,4
697,4,8,6,4,3,4,10,6,1,4
698,4,8,8,5,4,5,10,4,1,4

In [50]:
X = np.array(df.drop('class',axis=1))
y = np.array(df['class'])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size = 0.2)

clf = neighbors.KNeighborsClassifier()
clf.fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)
print(accuracy)

0.9714285714285714

In [60]:
example_measures = np.array([[4,2,4,5,3,2,4,2,1],[7,2,4,7,6,5,6,2,1],[3,2,4,1,3,6,4,3,1]])
example_measures = example_measures.reshape(len(example_measures), -1) # reshape for number of predictions
prediction = clf.predict(example_measures)
print(prediction)

[4 4 2]

In [58]:
X = np.array(df.drop('class',axis=1))
y = np.array(df['class'])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size = 0.2)

clf = svm.SVC(kernel = "linear")
clf.fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)
print(accuracy)

example_measures = np.array([[4,2,4,5,3,2,4,2,1],[7,2,4,7,6,5,6,2,1],[3,2,4,1,3,6,4,3,1]])
example_measures = example_measures.reshape(len(example_measures), -1) # reshape for number of predictions
prediction = clf.predict(example_measures)
print(prediction)

0.9428571428571428
[4 4 2]